from django.db import models

class WeatherData0(models.Model):
    index_name = models.CharField(max_length=100, primary_key=True) 
    type = models.CharField(max_length=100)
    spot = models.CharField(max_length=100)
    plot_1 = models.FloatField()
    plot_2 = models.FloatField()
    plot_3 = models.FloatField()
    plot_4 = models.FloatField()
    plot_5 = models.FloatField()
    plot_6 = models.FloatField()
    plot_7 = models.FloatField()
    plot_8 = models.FloatField()
    plot_9 = models.FloatField()
    plot_10 = models.FloatField()
    plot_11 = models.FloatField()
    plot_12 = models.FloatField()
    plot_13 = models.FloatField()
    plot_14 = models.FloatField()
    plot_15 = models.FloatField()
    plot_16 = models.FloatField()
    plot_17 = models.FloatField()
    plot_18 = models.FloatField()
    plot_19 = models.FloatField()
    plot_20 = models.FloatField()
    plot_21 = models.FloatField()
    plot_22 = models.FloatField()
    plot_23 = models.FloatField()
    plot_24 = models.FloatField()
    
class WeatherData1(models.Model):
    index_name = models.CharField(max_length=100, primary_key=True) 
    type = models.CharField(max_length=100)
    spot = models.CharField(max_length=100)
    plot_1 = models.FloatField()
    plot_2 = models.FloatField()
    plot_3 = models.FloatField()
    plot_4 = models.FloatField()
    plot_5 = models.FloatField()
    plot_6 = models.FloatField()
    plot_7 = models.FloatField()
    plot_8 = models.FloatField()
    plot_9 = models.FloatField()
    plot_10 = models.FloatField()
    plot_11 = models.FloatField()
    plot_12 = models.FloatField()
    plot_13 = models.FloatField()
    plot_14 = models.FloatField()
    plot_15 = models.FloatField()
    plot_16 = models.FloatField()
    plot_17 = models.FloatField()
    plot_18 = models.FloatField()
    plot_19 = models.FloatField()
    plot_20 = models.FloatField()
    plot_21 = models.FloatField()
    plot_22 = models.FloatField()
    plot_23 = models.FloatField()
    plot_24 = models.FloatField()
    
class DemandData0(models.Model):
    id = models.IntegerField(primary_key=True) 
    date = models.DateField()
    time = models.TimeField()
    ploperformancet = models.FloatField()
    prediction_q = models.FloatField(default=0.0)
    prediction_n = models.FloatField(default=0.0)
    used = models.FloatField()
    supply = models.FloatField()
    supply_prediction = models.FloatField()
    def __str__(self):
        return f"{self.date} {self.time}"

