# Generated by Django 4.2.2 on 2024-07-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('spot', models.IntegerField(default=0)),
                ('plot_1', models.IntegerField(default=0)),
                ('plot_2', models.IntegerField(default=0)),
                ('plot_3', models.IntegerField(default=0)),
                ('plot_4', models.IntegerField(default=0)),
                ('plot_5', models.IntegerField(default=0)),
                ('plot_6', models.IntegerField(default=0)),
                ('plot_7', models.IntegerField(default=0)),
                ('plot_8', models.IntegerField(default=0)),
                ('plot_9', models.IntegerField(default=0)),
                ('plot_10', models.IntegerField(default=0)),
                ('plot_11', models.IntegerField(default=0)),
                ('plot_12', models.IntegerField(default=0)),
                ('plot_13', models.IntegerField(default=0)),
                ('plot_14', models.IntegerField(default=0)),
                ('plot_15', models.IntegerField(default=0)),
                ('plot_16', models.IntegerField(default=0)),
                ('plot_17', models.IntegerField(default=0)),
                ('plot_18', models.IntegerField(default=0)),
                ('plot_19', models.IntegerField(default=0)),
                ('plot_20', models.IntegerField(default=0)),
                ('plot_21', models.IntegerField(default=0)),
                ('plot_22', models.IntegerField(default=0)),
                ('plot_23', models.IntegerField(default=0)),
                ('plot_24', models.IntegerField(default=0)),
            ],
        ),
    ]
