# Generated by Django 4.2.2 on 2024-07-29 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmd_gui', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friend',
            new_name='NewData',
        ),
    ]
