# Generated by Django 4.2.2 on 2024-07-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmd_gui', '0003_weatherdata_delete_newdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='index_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
