# Generated by Django 4.2.2 on 2024-07-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmd_gui', '0005_weatherdata1_rename_weatherdata_weatherdata0'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandData1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('ploperformancet', models.FloatField()),
                ('prediction', models.FloatField()),
                ('used', models.FloatField()),
                ('supply', models.FloatField()),
                ('supply_prediction', models.FloatField()),
            ],
        ),
    ]
