# Generated by Django 4.2.2 on 2024-07-30 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmd_gui', '0006_demanddata1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DemandData1',
            new_name='DemandData0',
        ),
    ]
