# Generated by Django 4.2.2 on 2024-08-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmd_gui', '0008_remove_demanddata0_prediction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_sensitivity_flag', models.BooleanField(default=True)),
            ],
        ),
    ]
