# Generated by Django 4.2.2 on 2024-08-14 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmd_gui', '0009_setting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
